### ISSUE TITLE
operating environment

### ISSUE THREAD

**Issue by zhanghui-svg** [MMorafah/Sub-FedAvg#1]
Can you tell me more about the operating environment? Thanks!

**Comment by MMorafah** [comment]
It's using linux Ubuntu 18 if that answers your question?! Please let me know if you have any issues running the code or understanding any parts! Thanks

**Comment by zhanghui-svg** [comment]
Thank you for your reply. I will try to simulate it.

**Comment by zhanghui-svg** [comment]
> It's using linux Ubuntu 18 if that answers your question?! Please let me know if you have any issues running the code or understanding any parts! Thanks

Thank you for your reply. I will try to simulate it
