### ISSUE TITLE
question

### ISSUE THREAD

**Issue by Yang-cpu502** [MMorafah/Sub-FedAvg#2]
Hello, I put the parameter settings in script_s.sh into the parameters under edit configurations under main_s.py, and when I ran the code, the following problems occurred:
usage: main_s.py [-h] [--rounds ROUNDS] [--num_users NUM_USERS]
                 [--nclass NCLASS] [--nsample_pc NSAMPLE_PC] [--frac FRAC]
                 [--local_ep LOCAL_EP] [--local_bs LOCAL_BS] [--bs BS]
                 [--lr LR] [--momentum MOMENTUM] [--warmup_epoch WARMUP_EPOCH]
                 [--model MODEL] [--ks KS] [--in_ch IN_CH] [--dataset DATASET]
                 [--noniid] [--shard] [--label] [--split_test]
                 [--pruning_percent_ch PRUNING_PERCENT_CH]
                 [--pruning_percent_fc PRUNING_PERCENT_FC]
                 [--pruning_target PRUNING_TARGET]
                 [--dist_thresh_ch DIST_THRESH_CH]
                 [--dist_thresh_fc DIST_THRESH_FC] [--acc_thresh ACC_THRESH]
                 [--sparsity-regularization] [--s S] [--weight-decay W]
                 [--gpu GPU] [--is_print] [--print_freq PRINT_FREQ]
                 [--seed SEED] [--load_initial LOAD_INITIAL]
main_s.py: error: unrecognized arguments: python main_s.py
May I ask what is the cause? It runs under the windows system.

**Comment by MMorafah** [comment]
Hi, I think the reason is you're running on windows kernel. Running the srcipt_s.sh on Linux machine or kernel should work. Please let me know if you are still having trouble running the script in Linux kernel.
